version: "3.8"

services:
  api_gateway:
    build:
      context: .
      dockerfile: ./Dockerfile-development
    restart: always
    container_name: api_gateway
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
