version: "3.8"

services:
  api_gateway:
    build:
      context: .
      dockerfile: ./Dockerfile-development
    restart: always
    container_name: api_gateway
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend_development
    depends_on:
      - rmq

  rmq:
    container_name: rmq
    image: rabbitmq:3-management
    env_file:
      - environment/.development.env
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - backend_development

networks:
  backend_development:
    name: telegram_network