FROM node:18.16-alpine AS build
WORKDIR /app
ADD package*.json ./
RUN npm install
ADD . .
RUN npm run build

FROM node:18.16-alpine AS production
WORKDIR /app
ADD package*.json ./
RUN npm install --only=prod --ignore-scripts
COPY --from=build /app/dist ./dist
COPY environment /app/environment
CMD ["npm", "run", "start:prod"]