name: Проверка и тестирование кода

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]

jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:18.16
    steps:
      - uses: actions/checkout@v3
      - name: Кэширование NodeJS модулей
        uses: actions/cache@v3
        env:
          cache-name: npm-${{ hashFiles('package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}
      - name: Установка npm зависимостей
        run: npm install
      - name: Линтинг исходного кода с ESLint
        run: npm run lint

  test:
    needs: eslint
    runs-on: ubuntu-latest
    container:
      image: node:18.16
    steps:
      - uses: actions/checkout@v3
      - name: Кэширование NodeJS модулей
        uses: actions/cache@v3
        env:
          cache-name: npm-${{ hashFiles('package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}
      - name: Установка npm зависимостей
        run: npm install
      - name: Тестирование исходного кода
        run: npm run test